# -*- coding: utf-8 -*-
"""Maratona.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TteeIJlW9zUFEa-YEerOCxteIwTGsH2R
"""

import numpy as np
import random

from datetime import datetime

input_list = np.array([' ','A', 'B', 'C','D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P','Q','R','S','T','U','V','W','X','Y','Z','0','1','2','3','4','5','6','7','8','9'])

input_dict = { x:y for x,y in zip(input_list,range(37))}

input_list

input_dict

print(input_dict.values())

code_dict = {'0' : ' ',
             '1' : 'A',
             '2' : 'B',
             '3' : 'C',
             '4' : 'D',
             '5' : 'E',
             '6' : 'F',
             '7' : 'G',
             '8' : 'H',
             '9' : 'I',
             '10' : 'J',
             '11' : 'K',
             '12' : 'L',
             '13' : 'M',
             '14' : 'N',
             '15' : 'O',
             '16' : 'P',
             '17' : 'Q',
             '18' : 'R',
             '19' : 'S',
             '20' : 'T',
             '21' : 'U',
             '22' : 'V',
             '23' : 'W',
             '24' : 'X',
             '25' : 'Y',
             '26' : 'Z',
             '27' : '0',
             '28' : '1',
             '29' : '2',
             '30' : '3',
             '31' : '4',
             '32' : '5',
             '33' : '6',
             '34' : '7',
             '35' : '8',
             '36' : '9'}

code_dict

import string
def codificar(text):
    new_char = ''
    for letter in text:
        var = int(input_dict[letter]+3)
        if var > 36:
            while var > 36:
                var -= 37
        var3=str(var)  
        new_char = new_char + code_dict[var3]
    print(new_char)


def decodificar(text):
    new_char = ''
    for letter in text:
        var = int(input_dict[letter]-3)
        if var < 0:
            while var < 0:
                var += 37
        var3=str(var)  
        new_char = new_char + code_dict[var3]
    print(new_char)

def Menu():
  print('-'*43)
  print('|         Escolha uma das opções          |')
  print('|         1 - Codificar Mensagem          |')
  print('|         2 - Decodificar Mensagem        |')
  print('-'*43)

  option = int(input('Digite a Opção escolhida: '))

  if option == 1:
    text = str(input('Digite um texto para ser codificado:')).upper()
    codificar(text)
  elif option == 2:
    text = str(input('Digite um texto para ser decodificado:')).upper()
    decodificar(text)

Menu()



"""# GDULRBB"""